// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/gate/gate_msg.proto

package gate

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GateMsgTest struct {
	I                    int32    `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	S                    string   `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateMsgTest) Reset()         { *m = GateMsgTest{} }
func (m *GateMsgTest) String() string { return proto.CompactTextString(m) }
func (*GateMsgTest) ProtoMessage()    {}
func (*GateMsgTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gate_msg_d9f7104a9820281c, []int{0}
}
func (m *GateMsgTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateMsgTest.Unmarshal(m, b)
}
func (m *GateMsgTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateMsgTest.Marshal(b, m, deterministic)
}
func (dst *GateMsgTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateMsgTest.Merge(dst, src)
}
func (m *GateMsgTest) XXX_Size() int {
	return xxx_messageInfo_GateMsgTest.Size(m)
}
func (m *GateMsgTest) XXX_DiscardUnknown() {
	xxx_messageInfo_GateMsgTest.DiscardUnknown(m)
}

var xxx_messageInfo_GateMsgTest proto.InternalMessageInfo

func (m *GateMsgTest) GetI() int32 {
	if m != nil {
		return m.I
	}
	return 0
}

func (m *GateMsgTest) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type GateMsgTestAck struct {
	IntList              []int32  `protobuf:"varint,1,rep,packed,name=intList,proto3" json:"intList,omitempty"`
	StrList              []string `protobuf:"bytes,2,rep,name=strList,proto3" json:"strList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GateMsgTestAck) Reset()         { *m = GateMsgTestAck{} }
func (m *GateMsgTestAck) String() string { return proto.CompactTextString(m) }
func (*GateMsgTestAck) ProtoMessage()    {}
func (*GateMsgTestAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_gate_msg_d9f7104a9820281c, []int{1}
}
func (m *GateMsgTestAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GateMsgTestAck.Unmarshal(m, b)
}
func (m *GateMsgTestAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GateMsgTestAck.Marshal(b, m, deterministic)
}
func (dst *GateMsgTestAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GateMsgTestAck.Merge(dst, src)
}
func (m *GateMsgTestAck) XXX_Size() int {
	return xxx_messageInfo_GateMsgTestAck.Size(m)
}
func (m *GateMsgTestAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GateMsgTestAck.DiscardUnknown(m)
}

var xxx_messageInfo_GateMsgTestAck proto.InternalMessageInfo

func (m *GateMsgTestAck) GetIntList() []int32 {
	if m != nil {
		return m.IntList
	}
	return nil
}

func (m *GateMsgTestAck) GetStrList() []string {
	if m != nil {
		return m.StrList
	}
	return nil
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_gate_msg_d9f7104a9820281c, []int{2}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (dst *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(dst, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAck struct {
	Error                string   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAck) Reset()         { *m = LoginAck{} }
func (m *LoginAck) String() string { return proto.CompactTextString(m) }
func (*LoginAck) ProtoMessage()    {}
func (*LoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_gate_msg_d9f7104a9820281c, []int{3}
}
func (m *LoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAck.Unmarshal(m, b)
}
func (m *LoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAck.Marshal(b, m, deterministic)
}
func (dst *LoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAck.Merge(dst, src)
}
func (m *LoginAck) XXX_Size() int {
	return xxx_messageInfo_LoginAck.Size(m)
}
func (m *LoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAck proto.InternalMessageInfo

func (m *LoginAck) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LoginAck) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*GateMsgTest)(nil), "gate.GateMsgTest")
	proto.RegisterType((*GateMsgTestAck)(nil), "gate.GateMsgTestAck")
	proto.RegisterType((*LoginReq)(nil), "gate.LoginReq")
	proto.RegisterType((*LoginAck)(nil), "gate.LoginAck")
}

func init() { proto.RegisterFile("pb/gate/gate_msg.proto", fileDescriptor_gate_msg_d9f7104a9820281c) }

var fileDescriptor_gate_msg_d9f7104a9820281c = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xc1, 0x4b, 0x04, 0x21,
	0x14, 0x06, 0x70, 0xdc, 0xcd, 0x6d, 0xe7, 0x15, 0x1d, 0x24, 0x16, 0xe9, 0x24, 0x9e, 0xec, 0x52,
	0x87, 0x2e, 0x1d, 0x5b, 0x28, 0x22, 0x98, 0x20, 0xa4, 0xce, 0x31, 0x33, 0x89, 0x48, 0x34, 0x4e,
	0xbe, 0x17, 0xfd, 0xfb, 0xa1, 0xe3, 0xc4, 0x5e, 0x84, 0x1f, 0xef, 0x7d, 0xfa, 0x09, 0xbb, 0xa9,
	0xbf, 0xf6, 0x1d, 0xb9, 0x72, 0xbc, 0x7f, 0xa1, 0xbf, 0x9a, 0x52, 0xa4, 0x28, 0x8e, 0xb2, 0xf5,
	0x25, 0x9c, 0x3c, 0x76, 0xe4, 0x9e, 0xd1, 0xbf, 0x3a, 0x24, 0x71, 0x0a, 0x2c, 0x48, 0xa6, 0x98,
	0xe1, 0x96, 0x85, 0x2c, 0x94, 0x2b, 0xc5, 0x4c, 0x63, 0x19, 0xea, 0x7b, 0x38, 0x3b, 0x58, 0xdd,
	0x0f, 0x9f, 0x42, 0xc2, 0x71, 0x18, 0xa9, 0x0d, 0x48, 0x92, 0xa9, 0xb5, 0xe1, 0x76, 0x61, 0x9e,
	0x20, 0xa5, 0x32, 0x59, 0xa9, 0xb5, 0x69, 0xec, 0x42, 0x7d, 0x07, 0xdb, 0x36, 0xfa, 0x30, 0x5a,
	0xf7, 0x9d, 0xb7, 0xf6, 0xc3, 0x10, 0x7f, 0x46, 0x2a, 0x6f, 0x36, 0x76, 0xa1, 0xb8, 0x80, 0xed,
	0x4b, 0x87, 0xf8, 0x1b, 0xd3, 0x47, 0x2d, 0xf0, 0x6f, 0x7d, 0x5b, 0x6f, 0xc8, 0x0d, 0xce, 0x81,
	0x3f, 0xa4, 0x14, 0x53, 0xcd, 0xcf, 0x10, 0x3b, 0xd8, 0xbc, 0xa1, 0x4b, 0x4f, 0x73, 0x96, 0xdb,
	0xaa, 0x7e, 0x53, 0x7e, 0x7e, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0x57, 0x51, 0x26, 0x6a, 0x13,
	0x01, 0x00, 0x00,
}
