// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/stream.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamFrameType int32

const (
	StreamFrameType_Message StreamFrameType = 0
	StreamFrameType_Kick    StreamFrameType = 1
	StreamFrameType_Ping    StreamFrameType = 2
)

var StreamFrameType_name = map[int32]string{
	0: "Message",
	1: "Kick",
	2: "Ping",
}
var StreamFrameType_value = map[string]int32{
	"Message": 0,
	"Kick":    1,
	"Ping":    2,
}

func (x StreamFrameType) String() string {
	return proto.EnumName(StreamFrameType_name, int32(x))
}
func (StreamFrameType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_stream_2aecb914e51dadf5, []int{0}
}

type StreamFrame struct {
	Type                 StreamFrameType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.StreamFrameType" json:"Type,omitempty"`
	MsgId                int32           `protobuf:"varint,2,opt,name=MsgId,proto3" json:"MsgId,omitempty"`
	MsgData              []byte          `protobuf:"bytes,3,opt,name=MsgData,proto3" json:"MsgData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StreamFrame) Reset()         { *m = StreamFrame{} }
func (m *StreamFrame) String() string { return proto.CompactTextString(m) }
func (*StreamFrame) ProtoMessage()    {}
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_stream_2aecb914e51dadf5, []int{0}
}
func (m *StreamFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamFrame.Unmarshal(m, b)
}
func (m *StreamFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamFrame.Marshal(b, m, deterministic)
}
func (dst *StreamFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamFrame.Merge(dst, src)
}
func (m *StreamFrame) XXX_Size() int {
	return xxx_messageInfo_StreamFrame.Size(m)
}
func (m *StreamFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamFrame.DiscardUnknown(m)
}

var xxx_messageInfo_StreamFrame proto.InternalMessageInfo

func (m *StreamFrame) GetType() StreamFrameType {
	if m != nil {
		return m.Type
	}
	return StreamFrameType_Message
}

func (m *StreamFrame) GetMsgId() int32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *StreamFrame) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func init() {
	proto.RegisterType((*StreamFrame)(nil), "pb.StreamFrame")
	proto.RegisterEnum("pb.StreamFrameType", StreamFrameType_name, StreamFrameType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Stream_StreamClient, error)
}

type streamClient struct {
	cc *grpc.ClientConn
}

func NewStreamClient(cc *grpc.ClientConn) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Stream_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Stream_serviceDesc.Streams[0], "/pb.Stream/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamStreamClient{stream}
	return x, nil
}

type Stream_StreamClient interface {
	Send(*StreamFrame) error
	Recv() (*StreamFrame, error)
	grpc.ClientStream
}

type streamStreamClient struct {
	grpc.ClientStream
}

func (x *streamStreamClient) Send(m *StreamFrame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamStreamClient) Recv() (*StreamFrame, error) {
	m := new(StreamFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServer is the server API for Stream service.
type StreamServer interface {
	Stream(Stream_StreamServer) error
}

func RegisterStreamServer(s *grpc.Server, srv StreamServer) {
	s.RegisterService(&_Stream_serviceDesc, srv)
}

func _Stream_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).Stream(&streamStreamServer{stream})
}

type Stream_StreamServer interface {
	Send(*StreamFrame) error
	Recv() (*StreamFrame, error)
	grpc.ServerStream
}

type streamStreamServer struct {
	grpc.ServerStream
}

func (x *streamStreamServer) Send(m *StreamFrame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamStreamServer) Recv() (*StreamFrame, error) {
	m := new(StreamFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Stream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Stream_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/stream.proto",
}

func init() { proto.RegisterFile("pb/stream.proto", fileDescriptor_stream_2aecb914e51dadf5) }

var fileDescriptor_stream_2aecb914e51dadf5 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x48, 0xd2, 0x2f,
	0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x4a, 0xe3, 0xe2, 0x0e, 0x06, 0x8b, 0xb9, 0x15, 0x25, 0xe6, 0xa6, 0x0a, 0xa9, 0x73, 0xb1, 0x84,
	0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0xeb, 0x15, 0x24, 0xe9, 0x21,
	0x49, 0x83, 0xa4, 0x82, 0xc0, 0x0a, 0x84, 0x44, 0xb8, 0x58, 0x7d, 0x8b, 0xd3, 0x3d, 0x53, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x21, 0x09, 0x2e, 0x76, 0xdf, 0xe2, 0x74, 0x97,
	0xc4, 0x92, 0x44, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x57, 0xcb, 0x88, 0x8b, 0x1f,
	0xcd, 0x20, 0x21, 0x6e, 0x2e, 0x76, 0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x01, 0x06, 0x21,
	0x0e, 0x2e, 0x16, 0xef, 0xcc, 0xe4, 0x6c, 0x01, 0x46, 0x10, 0x2b, 0x20, 0x33, 0x2f, 0x5d, 0x80,
	0xc9, 0xc8, 0x8a, 0x8b, 0x0d, 0xa2, 0x47, 0xc8, 0x00, 0xce, 0xe2, 0x47, 0x73, 0x92, 0x14, 0xba,
	0x80, 0x12, 0x83, 0x06, 0xa3, 0x01, 0x63, 0x12, 0x1b, 0xd8, 0x8b, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x99, 0x6f, 0x5e, 0xe7, 0xf5, 0x00, 0x00, 0x00,
}
